version: "3.7"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - flask
      - react
    networks:
      - webnet

  flask:
    build: ./flask
    container_name: flask
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./flask:/app
    expose:
      - "5000"
    networks:
      - webnet

  react:
    build: ./node
    container_name: react
    volumes:
      - ./react:/app
    ports:
      - "3000:3000"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email tijmenbaas83@outlook.com --agree-tos --no-eff-email -d docktertest.tech-boss.nl
    depends_on:
      - nginx
    networks:
      - webnet

networks:
  webnet:
